CREATE DATABASE NHANSU

USE NHANSU

--Tạo bảng CHUCVU
CREATE TABLE CHUCVU (
    MaCV VARCHAR(20),
    TenCV NVARCHAR(50) NOT NULL,
	PRIMARY KEY (MaCV)
)

--Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(20),
    HoTen NVARCHAR(50) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh NVARCHAR(10),
    DiaChi NVARCHAR(70),
    SDT CHAR(10) NOT NULL,
    MaCV VARCHAR(20),
	PRIMARY KEY (MaNV),
    FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV)
)

--Tạo bảng TAIKHOAN
CREATE TABLE TAIKHOAN (
    MaTK VARCHAR(20),
    TenDangNhap VARCHAR(50) NOT NULL CONSTRAINT UQ_TenDangNhap_TK UNIQUE,
    MatKhau VARCHAR(50) NOT NULL,
    MaNV VARCHAR(20),
	PRIMARY KEY (MaTK),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
)

--Tạo bảng LUONG
CREATE TABLE LUONG (
    MaLuong VARCHAR(20),
    MaNV VARCHAR(20),
    LuongTheoGio FLOAT,
	CONSTRAINT CK_LTG CHECK (LuongTheoGio>0),
    Thuong FLOAT, 
	CONSTRAINT CK_Thuong CHECK (Thuong>=0),
    Phat FLOAT,
	CONSTRAINT CK_Phat CHECK (Phat>=0),
	PRIMARY KEY (MaLuong),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
)

--Tạo bảng CHAMCONG
CREATE TABLE CHAMCONG (
    MaCC VARCHAR(20),
    MaNV VARCHAR(20),
    Ngay DATE NOT NULL,
    GioVao TIME NOT NULL,
    GioRa TIME NOT NULL,
	PRIMARY KEY (MaCC),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
)
